Raku/ecosystem

META.list
Update proposal because of transfer of two modules from bbkr to MARTIMM
=> Transfer of two modules

META.list
Hi,
first up of the ports of as many of the https://metacpan.org/author/JSTOWE, this one because it was the easiest :)
=> Add Linux::Fuser to the modules list

META.list
Hi, 
The following is a native perl6 implementation of the Apache Avro data serialization system.
=> added Avro

META.list
=> Add Ident::Client

META.list
Hi,
Could you add my new module App::Mi6, which is a minimal authoring tool for Perl6?
Thanks.
=> Add App::Mi6

META.list
And remove a no longer needed module
=> Add Router::Boost

META.list
=> add Config::TOML

META.list
well ...  i don't know what to write in this PR :) Rototo is an attempt to produce xml and html a way i'm confortable with. i'll be gratefull if you add it to eco
=> add Rototo to eco

META.list
See https://github.com/ShaneKilkelly/perl6-config-clever
=> Add Config::Clever to ecosystem

META.list
add https://github.com/shoichikaji/Frinfon, a minimal sinatra.
=> add Frinfon

META.list
See https://github.com/shoichikaji/Data-Section-Simple
=> Add Data::Section::Simple to ecosystem

META.list
See https://github.com/Skarsnik/perl6-gumbo
=> Add Gumbo to ecosystem

META.list
Documentation and tests are currently lacking, but will be updated over the next several days!
=> Added Raspberry Pi module to META.list

META.list
See https://github.com/hartenfels/Text-Markdown-Discount
=> Add Text::Markdown::Discount to ecosystem

META.list
See https://github.com/kolikov/perl6-Lingua-EN-Conjugate.git
=> Please Add Lingua::EN::Conjugate

META.list
A simple modufle for configuration files
=> Add Config::Simple

META.list
See https://github.com/bluebear94/Terminal-WCWidth
=> Add Terminal::WCWidth to the ecosystem

META.list
Adds Google's Brotli compression see https://github.com/sylvarant/Compress-Brotli
=> Added Compress::Brotli

META.list
See https://github.com/pierre-vigier/Perl6-HTTP-Signature
=> Add HTTP::Signature

META.list
See https://github.com/Demayl/perl6-Email-Valid
=> Add Email::Valid

META.list
See https://github.com/hartenfels/Javascript-SpiderMonkey
=> Add JavaScript::SpiderMonkey to ecosystem

META.list
https://github.com/bluebear94/Math-Random
=> Add Math::Random

META.list
https://github.com/pierre-vigier/Perl6-Math-Matrix
=> Add Math::Matrix for some matrix operations

META.list
**Haikunator - (https://github.com/Atrox/haikunatorperl)**
*Generate Heroku-like random names to use in your perl 6 applications.*
=> Add Haikunator

META.list
See https://github.com/nkh/P6-Data-Dump-Tree.git
=> Add Data::Dump::Tree to ecosystem

META.list
see https://github.com/bradclawsie/Hash-Consistent
=> Added Hash::Consistent

META.list
See https://github.com/yowcow/p6-String-CamelCase
=> Add String::CamelCase

META.list
Adding reference to my Perl 6 implementation of an Apache Kafka client.
=> Adding PKafka

META.list
=> Add AWS::Pricing to ecosystem

META.list
See https://github.com/ppentchev/Serialize-Naive
=> Add Serialize::Naive to the ecosystem.

META.list
Rough variant of bzlib2 native bindings: just bunch of signatures and tests. High-level API for it will be later.
=> Add Compress::Bzip2::Raw.

META.list
Add Build::Graph and Build::Simple to the module list
=> Add Build::Graph and Build::Simple

META.list
Some things are still in progress, but it works already. Also, I think, we should update bindings.md accordingly.
=> Bzlib2 bindings.

META.list
add WebService::AWS::V4 module
=> add WebService::AWS::V4

META.list
See https://github.com/salortiz/p6-LMDB
My first contribution to perl6 ecosystem, wanting comments, guidance  and generate discussion.
=> Add p6-LMDB to ecosystem

META.list
See https://github.com/rightfold/Module-Skeleton
=> Add Module::Skeleton to ecosystem

META.list
Hi
I implemented Aho-Corasick algorithm in perl6.
=> Add p6-Algorithm-AhoCorasick

META.list
See https://github.com/pierre-vigier/Perl6-AttrX-Lazy
=> Add AttrX::Lazy

META.list
See https://github.com/rightfold/Inline-FALSE
=> Add Inline::FALSE

META.list
Currently provides completions and ctags at the command line for integration with text editor plugins.  Adding a cascading customizable linter next. Then maybe test coverage, code formatter, and refactoring tools.
https://github.com/MadcapJake/p6dx
=> Add App::P6Dx

META.list
=> Added LendingClub module.

META.list
See https://github.com/yowcow/p6-WebService-SOP
=> add WebService::SOP

META.list
Sorry to bother you :)
* I changed username.
* prefer META6.json to META.info.
=> Fix some urls

META.list
Fix Task::Star build
https://github.com/hoelzro/p6-linenoise/commit/46f9534b1568e68a2a077ee80713914738b16e28
=> hoelzro has switched linenoise to meta6.info

META.list
See https://github.com/okaoka/p6-Algorithm-Treap
=> Add Algorithm::Treap to ecosystem

META.list
See https://github.com/kuerbis/Term-Choose-p6
=> Add Term-Choose-p6 to ecosystem

META.list
Hi,
I looked into the IO::Prompt module which resides in the shelter repos and forked it to improve my perl6 skills a bit.
Tests passes and I hope it is usefull.
=> Add new module IO::Prompt

META.list
See https://github.com/okaoka/p6-Algorithm-BinaryIndexedTree
=> Add Algorithm-BinaryIndexedTree to ecosystem

META.list
=> Move to META6.json

META.list
RPG-style dice string rolling tool: https://github.com/jamesneko/dice-roller
=> Add Dice::Roller to ecosystem

META.list
See https://github.com/okaoka/p6-Algorithm-ZobristHashing
=> Add Algorithm::ZobristHashing to ecosystem

META.list
See https://github.com/okaoka/p6-Algorithm-TernarySearchTree
=> Add Algorithm::TernarySearchTree

META.list
See https://github.com/PowellDean/Locale-Codes-Country.git
=> Add Locale-Codes-Country to ecosystem

META.list
This is a WIP port of the Perl5 Scientist module into Perl6.
It does not have all features yet.
=> Add new Scientist module

META.list
Aims to be like JSON Pointer / Patch for p6 containers, with diff/patch NYI
https://github.com/atweiden/crane
=> Add module Crane

META.list
See https://github.com/okaoka/p6-Algorithm-KdTree
=> Add Algorithm::KdTree to ecosystem

META.list
See https://github.com/okaoka/p6-Algorithm-MinMaxHeap
=> Add Algorithm::MinMaxHeap to ecosystem

META.list
See https://github.com/kuerbis/Term-Choose-Util-p6
Add Term::TablePrint to ecosystem
See https://github.com/kuerbis/Term-TablePrint-p6
=> Add Term::Choose::Util to ecosystem

META.list
See https://github.com/kmwallio/Acme-Skynet
=> Add Acme::Skynet to ecosystem

META.list
See https://github.com/titsuki/p6-Algorithm-SetUnion
=> Add Algorithm::SetUnion to ecosystem

META.list
See https://github.com/titsuki/p6-Algorithm-Kruskal
=> Add Algorithm::Kruskal to ecosystem

META.list
See https://github.com/kmwallio/p6-Lingua-EN-Stopwords
=> Add Lingua::EN::Stopwords

META.list
See https://github.com/kmwallio/p6-Text-TFIdf
=> Add Text::TFIdf

META.list
See https://github.com/titsuki/p6-Algorithm-Manacher
=> Add Algorithm::Manacher to ecosystem

META.list
See https://github.com/0racle/p6-wig
=> Add wig to ecosystem

META.list
See https://github.com/kuerbis/Term-Form-p6
=> Add Term::Form to ecosystem

META.list
Friendly password-hashing on top of a libargon2 binding.
=> Add Crypt::Argon2

META.list
Add TelegramBot to ecosystem; see https://github.com/GildedHonour/TelegramBot
=> Add TelegramBot to ecosystem

META.list
See https://github.com/yowcow/p6-Algorithm-BloomFilter 🙇
=> Add Algorithm::BloomFilter to ecosystem

META.list
See https://github.com/Altai-man/perl6-Devel-Trace
=> Add Devel::Trace to ecosystem

META.list
[TXN::Parser](https://github.com/atweiden/txn-parser)
=> Add module TXN::Parser

META.list
Add Audio::OggVorbis to the perl6 ecosystem.
=> New Perl6 Module

META.list
See https://github.com/titsuki/p6-App-AizuOnlineJudge
=> Add App::AizuOnlineJudge to ecosystem

META.list
See https://github.com/titsuki/p6-Term-Readsecret
=> Add Term::Readsecret to ecosystem

META.list
I changed the module name and its URL.
=> Fix Term::Readsecret to Terminal::Readsecret

META.list
See https://github.com/MasterDuke17/Text-Diff-Sift4
=> Add Text::Diff::Sift4 to ecosystem

META.list
Repo: https://github.com/araraloren/Getopt-Kinoko
=> Add Getopt::Kinoko

META.list
Add Digest::MurmurHash3 to ecosystem.
See https://github.com/yowcow/p6-Digest-MurmurHash3.
=> Add Digest::MurmurHash3

META.list
See https://github.com/kalkin/perl6-hashids
=> Add Hashids to ecosystem

META.list
See https://github.com/Altai-man/p6-WWW-DuckDuckGo
=> Add WWW::DuckDuckGo to the ecosystem

META.list
See https://github.com/titsuki/p6-Algorithm-NaiveBayes
=> Add Algorithm::NaiveBayes to ecosystem

META.list
See https://github.com/MARTIMM/config-datalang-refine but pod file is better
=> Add Config::DataLang::Refine to ecosystem

META.list
See https://github.com/Altai-man/perl6-Config-Netrc/
=> Add Config::Netrc

META.list
See https://github.com/melezhik/sparrowdo
=> Add sparrowdo to ecosystem

META.list
See https://github.com/bduggan/mosdef
=> Add Slang::Mosdef to ecosystem

META.list
Execute a command and capture its exit code and output.
See https://github.com/ppentchev/Shell-Capture
=> Add Shell::Capture to the ecosystem.

META.list
See https://github.com/bbkr/TinyID
=> Added TinyID: Shorten and obfuscate IDs

META.list
[File::Presence](https://github.com/atweiden/file-presence)
=> Add module File::Presence

META.list
See https://gitlab.com/samcns/uzu
=> Add Uzu to ecosystem

META.list
Hi!
Here's a new module for the ecosystem.
thanks
Brian
=> added oauth2-client-google

META.list
See https://github.com/ajs/perl6-Math-Arrow
=> Add Math::Arrow to ecosystem

META.list
See https://github.com/shantanubhadoria/p6-Printer-ESCPOS
=> Add Printer::ESCPOS to ecosystem

META.list
See https://github.com/shantanubhadoria/p6-CompUnit-Search
Simple CompUnit Search in CompUnit::Repository::Installation Repositories as the first step for implementing a pluggable role. More Repo type support will be added as things mature.
=> Add CompUnit::Search to ecosystem

META.list
See https://github.com/pierre-vigier/Perl6-Acme-Sudoku
=> Add Acme::Sudoku to ecosystem

META.list
See https://github.com/ahalbert/perl6-itertools
=> Added python::itertools to ecosystem

META.list
Partly implemented (client side) Salted Challenge Response Authentication Mechanism
(SCRAM) according to rfc5802.
=> Authentication methods using SCRAM

META.list
https://github.com/melezhik/sparrowdo-archive
=> Extract various archives using tar/unzip programs

META.list
See https://github.com/ajs/perl6-Math-Sequences
=> Add Math::Sequences to ecosystem

META.list
[Double-entry accounting ledger file format converter](https://github.com/atweiden/txn-remarshal)
=> Add module TXN::Remarshal

META.list
See https://github.com/ramiroencinas/perl6-FileSystem-Capacity
=> Add perl6-FileSystem-Capacity

META.list
See https://github.com/pierre-vigier/Perl6-Data-MessagePack
=> Add Data::MessagePack to ecosystem

META.list
See https://github.com/titsuki/p6-Algorithm-LBFGS
=> Add Algorithm::LBFGS to ecosystem

META.list
https://github.com/FCO/ProblemSolver
=> Add ProblemSolver

META.list
Hi,
Here's a new module for the ecosystem.
thanks
Brian
=> p6-Crypt-RSA

META.list
See https://github.com/bduggan/p6-digest-sha1-native
=> Add Digest::SHA1::Native to ecosystem

META.list
Add Log::Async.  See https://github.com/bduggan/p6-log-async
=> add Log::Async

META.list
See https://github.com/titsuki/p6-MeCab
=> Add MeCab to ecosystem

META.list
See https://github.com/hipek8/p6-Statistics-LinearRegression
=> Added Statistics::LinearRegression

META.list
add module for parsing xls with freexl
=> add module

META.list
see https://github.com/hipek8/p6-UNIX-Daemonize
=> Add UNIX::Daemonize

META.list
See https://github.com/akiym/JSON-Hjson
=> Add JSON::Hjson to ecosystem

META.list
Run chef client on remote host using Sparrowdo.
=> Add Sparrowdo::Chef::Client to ecosystem

META.list
See https://github.com/dugword/Number-Bytes-Human
=> Add Number::Bytes::Human to ecosystem. 

META.list
A few Math and Physics constants, in Unicode.
=> Add Math::Constants to ecosystem

META.list
=> add Net::IP::Parse to ecosystem. See https://github.com/bradclawsie/Net::IP::Parse

META.list
https://github.com/FCO/Test-Fuzz
=> Adding Test::Fuzz to the ecosystem

META.list
see https://github.com/finanalyst/p6-inform
=> adding Informative (popup dialog box) to ecosystem

META.list
https://github.com/FCO/DateTime-Extended
=> Adding DateTime::Extended to the ecosystem

META.list
See https://github.com/titsuki/p6-Algorithm-LibSVM
=> Add Algorithm::LibSVM to ecosystem

META.list
My first Perl6 module (still in very early development). I hope, everything is correct like this.
=> Add Fortran::Grammar to META.list

META.list
added https://github.com/bradclawsie/DB-Rscs
=> added DB-Rscs

META.list
Context class inspired by Go's context package.
=> add Context

META.list
See https://github.com/7ojo/perl6-git-simple
=> Add Git::Simple to ecosystem

META.list
See https://github.com/7ojo/perl6-powerline-prompt
=> Add Powerline::Prompt to ecosystem

META.list
See https://github.com/scmorrison/perl6-Web-Cache
=> Add Web::Cache to ecosystem

META.list
See https://github.com/7ojo/perl6-platform
=> Add Platform to ecosystem

META.list
See https://github.com/blippy/perl6-ncurses6
=> Add NCurses6 to ecosystem

META.list
=> AWS::Pricing META.info > META6.json

META.list
=> use modern META name

META.list
=> Add TagLibC

META.list
=> Add Config

META.list
=> Add PostCocoon::Url

META.list
=> Add Config::Parser::yaml

META.list
- [x ] I **agree** to the usage of the META file as listed [here](https://github.com/perl6/ecosystem#legal).
- [ x] I have a license field listed in my META file that is one of https://spdx.org/licenses
=> ADDED: P6-Grammar-Tracer-Compact

META.list
=> Add Config::Parser::toml

META.list
See https://github.com/CurtTilmes/perl6-dbi-async
=> Add DBI::Async to ecosystem

META.list
See https://github.com/CurtTilmes/perl6-libcurl
- [X ] I **agree** to the usage of the META file as listed [here](https://github.com/perl6/ecosystem#legal).
- [X ] I have a license field listed in my META file that is one of https://spdx.org/licenses
=> Add LibCurl to ecosystem

META.list
=> Add Terminal::Table version 0.0.1 to the ecosystem

META.list
=> Add MPD::Client

META.list
=> add Log distribution

META.list
=> Update META.list with EC-Grammars-DIG

META.list
See https://github.com/svekenfur/Swedish-TextDates_sv.git
=> Add Swedish-Textdates to ecosystem

META.list
See https://github.com/albastev/Grammar-Modelica
- [X ] I **agree** to the usage of the META file as listed [here](https://github.com/perl6/ecosystem#legal).
- [ X] I have a license field listed in my META file that is one of https://spdx.org/licenses
=> Add Grammar::Modelica to ecosystem

META.list
=> Add japhb/Text-MiscUtils to ecosystem

META.list
=> Add Object::Container

META.list, PULL_REQUEST_TEMPLATE.md
See https://github.com/jaldhar/Algorithm-DawkinsWeasel
=> Add Algorithm::DawkinsWeasel to ecosystem

META.list
I'm new to this whole Perl 6 module thing.  Please forgive me for anything I might've missed procedure-wise.
=> Add GLFW to ecosystem

META.list
=> Add Text-UpsideDown to ecosystem

META.list
=> Add HTML::Escape

META.list
=> Add App::Miroku

META.list
=> Added WWW::SilverGoldBull package

META.list
See https://github.com/scovit/NativeHelpers-CBuffer
=> Add NativeHelpers::CBuffer to ecosystem

META.list
=> Add IRC::Client::Plugin::Github

META.list
See https://github.com/paulohrpinheiro/Brazilian-FederalDocuments
=> Add Brazilian::FederalDocuments to ecosystem

META.list
CucumisSextus is a Cucumber-like BDD test framework, see https://github.com/robertlemmen/perl6-cucumis-sextus
=> Add CucumisSextus to ecosystem

META.list
See https://github.com/titsuki/p6-Geo-Hash
=> Add Geo::Hash to ecosystem

META.list
See https://github.com/patzim/RPi-Device-ST7036
=> Add RPi::Device::ST7036 to ecosystem

META.list
=> Add MPD::AutoQueue to META.list

META.list
=> Remove scriptkitties modules, now released through CPAN

META.list
=> Remove App::MPD::AutoQueue, now available on CPAN

META.list
=> Add Operator::grandpa

META.list
=> Add Scheduler::DRMAA

META.list
=> RPi::Device:ST7036 moved to CPAN

META.list
=> Add Algorithm::BitMap

META.list
=> Add SQL::Lexer

META.list
=> Update Ddt to v0.4.3

META.list
`Test::Declare` is a rudimentary way to express test scenarios in a fairly declarative sense. Assuming I understand the word 'declarative' properly.
In this …
=> Add https://github.com/darrenf/p6-test-declare

META.list
=> add File::Path::Resolve

META.list
=> Add Git::Log module

META.list
This is a change of an existing module that's META file has been renamed.
=> HTTP::Status META File updated 7 days ago

META.list
See https://gitlab.com/pheix/router-right-perl6
🦋🦋🦋
=> Add Router::Right to ecosystem

META.list
easy-to-use simple learning, and support for multiple languages, such as C, C++, Perl 6, shell, Objective-C .
=> CCLog Simple and lightweight cross-platform logs

META.list
See https://github.com/shintakezou/Xmav-JSON
=> Add Xmav::JSON to ecosystem

META.list
Simple draw chart for Perl 6 , easy-to-use simple learning.
=> add CCChart

META.list
=> Begin adding tobs' modules

META.list
=> Add Bio::ViennaNGS

META.list
=> Add Avolution::Emoji

META.list
=> Update META.list with the BCP57 module

META.list
=> Update META.list with the p6-Calculator.

.travis.yml, META.list
Specifically created to test META. Takes around 1/20th of the time to test new modules.
=> Uses a new Travis environment

META.list
=> Trims spaces

META.list
=> Add UserLanguage module

META.list
=> Add API::Perspective to ecosystem

META.list
=> add P6TK module to the list

META.list
=> New Math::ConvergenceMethods module

META.list
=> Add Intl-CLDR

META.list
=> Add vCard::Parser

META.list
=> Add Command::Despatch module to ecosystem

META.list
=> Add Cro::LDAP::ASN::Plugin

META.list
https://github.com/allsopp/p6-Operator-dB
=> Add Operator::dB

META.list
See https://github.com/Demayl/perl6-Sys-IP
=> Add Sys::IP to the ecosystem

META.list
See https://github.com/tmtvl/neural-net
=> Add Neural::Net to ecosystem

META.list
=> Changes place (to pass tests)

META.list
https://gitlab.com/pheix/lzw-revolunet-perl6
👻
=> Add LZW::Revolunet to ecosystem

META.list
https://github.com/hythm7/Pakku
=> Add Pakku to ecosystem

META.list
=> Add Carp to the ecosystem

META.list
=> Move to new quarters

META.list
=> Add Raku-LLVM

META.list
- [] I have a license field listed in my META file that is one of https://spdx.org/licenses
=> Moved to CPAN

META.list
See https://github.com/nxadm/SuperMAIN
=> Add SuperMAIN to ecosystem

META.list
=> module moved to CPAN

META.list
See https://github.com/robertlemmen/raku-readwritelock
=> Add ReadWriteLock to ecosystem

META.list
=> Template::Mustache moving to CPAN

META.list
---
New location: https://modules.raku.org/dist/Matrix::Client:cpan:MATIASL
=> Matrix::Client moved to CPAN

META.list
=> Add Zap Module

META.list
=> Add Test::Script

META.list
=> Add Radamsa to ecosystem. See https://github.com/ddlws/radamsa-raku

META.list
=> Add Text::Slugify

META.list
=> Cmark , travis tests passing

META.list
=> RE-adds Lingua::En::Stem::Porter

META.list
While this PR is accepted: https://github.com/azawawi/perl6-sdl2/pulls
=> Add a working auth version of SDL2 to the ecosystem

META.list
=> Adds cmark::Simple

META.list
=> Adds kazmath

META.list
=> Adds Sys::Chown

META.list
=> Update location Datetime::Math

META.list
Test::META test passing with :relaxed-name
=> Adding Pod::From::Cache to the Ecosystem

PULL_REQUEST_TEMPLATE.md, README.md, docs/Hacktoberfest.md, tools/meta.p6
Track some things that have new URLS/names (not modules in the ecosystem)
=> some Perl6 -> Raku updates

META.list
=> Add Grammar::Message

META.list
=> I renamed the repo on github for META6::bin.

META.list
=> add Shell::Piping

META.list
This is needed for the `Shell::DSL` PR.
=> Add my fork of Fcntl module

META.list
=> Add my Shell::DSL module to the list

META.list
=> remove duplicate from META.list

META.list
=> Add Test::Inline

README.md
see: https://github.com/Raku/ecosystem/issues/391
=> Document the lack of assurance for valid META6-fragments

META.list
=> Change drforr/perl6-readline to fooist/perl6-readline

META.list
URL: https://github.com/codesections/pod-weave
=> Add Pod::Weave

META.list
URL: https://github.com/codesections/pod-tangle
=> Add Pod::Tangle

META.list
See https://github.com/juliodcs/BigRoot
=> Add BigRoot to ecosystem

META.list
=> Reissue Netstring

META.list
=> Add new modules

META.list
@JJ These two modules can be added together since they don't depend on each other.
=> Add Pakku::Meta and Pakku::RecMan::Client

META.list
=> Add Pakku::RecMan

META.list
A distribution that offers an unified API to dependencies (for the time being)
=> Adds Dist::META to ecosystem

META.list
=> add Operator::DynvarOr

META.list
This PR is first of two replacing the PR https://github.com/Raku/ecosystem/pull/503
=> Add License::Software v0.3.1

META.list
=> Re-add Pakku to the Ecosystem

META.list
=> Add new module Retry

META.list
Changes to new-name for re-release and check of the new META6.json
=> Updates to new URL for re-release

META.list
See https://github.com/littlebenlittle/stache
=> Add Stache to ecosystem

META.list
Updates the repo URL for `API::Discord`.
=> update repo link for API::Discord

META.list
=> Add META6::Query and FileSystem::Helpers to ecosystem

META.list
See https://github.com/alabamenhu/DebugTransput
=> Add Debug::Transport to list

META.list
=> Add new Bio module. See https://github.com/schmidt73/Bio.

META.list
=> Add Intl::Format::List to the ecosystem

META.list
https://github.com/finanalyst/raku-config
=> Add RakuConfig to ecosystem

META.list
https://github.com/finanalyst/collection
Is a base for distributions to render specific collections. Provides infrastructure for rendering a collection with raku program plugins.
=> Add Collection module to ecosystem

META.list
=> Add Intl::Format::Unit and Intl::Number::Plural

META.list
=> renamed repo "perl6-log" to "raku-log"

META.list
=> Add Intl::LanguageTaggish & Intl::LanguageTag::Simple

META.list
=> renamed repo

META.list
see https://github.com/khalidelboray/Pastebin-Pasteee
=> Add Pastebin::Pasteee to ecosystem

META.list
=> new module 'Hematite::Middleware::Session'

META.list
See https://github.com/stuart-little/RakuRename
=> Add RakuRename to ecosystem

META.list
See https://github.com/stuart-little/raku-data-tree
=> Add Data::Tree to ecosystem

META.list
This fixes kalkin/Ddt/issues/10
=> Update DDT and its dependency License::Software

META.list
See https://github.com/stuart-little/raku-file-directory-bubble
=> Add File::Directory::Bubble to ecosystem

META.list
=> Rename API::Perspective repo

META.list
=> add Mac::Applications::List module

META.list
=> rm Mac::Applications::List from p6c

META.list
Yes yes yes, I'll get to zef soon, I promise.
=> Add Token::Foreign to the ecosystem

META.list
https://github.com/shuppet/raku-mint
=> Add Mint module to ecosystem

META.list
=> handover perl6-Inline-Scheme-Gambit to iynehz

META.list
I will move it to the fez ecosystem in the future along with other modules
=> Add Terminal::Size to the ecosystem

META.list
they live now in the fez ecosystem
=> remove Email::Valid Sys::IP and Terminal::Size

META.list
Now it lives in the "zef ecosystem"
=> Remove finite-fields

META.list
=> rename branch from master to main
