META.list

Bindings to the Tiny C Compiler
cf https://github.com/cygx/p6-tinycc

Add TinyCC to the ecosystem

---

META.list

A Unicode encoding scheme suitable for name mangling
cf https://github.com/cygx/p6-uni63

Add Uni63 to the ecosystem

---

META.list

Adds the Editsrc::Uggedit module to the module list. The module is, "The obvious in-source Perl6 based solution to avoid repetion in modifing text by using embedded code with your languages of choice, or just scanning using a perl6 module."

Adds Editsrc::Uggedit to META.list

---

META.list

Add module https://github.com/nunorc/p6-Pekyll to the list.

Add new module: Pekyll

---

META.list

Raw::Socket is a low level BSD socket wrapper using NativeCall.

Added Raw::Socket

---

META.list

This is port of miyagawa's perl5 HTTP::Tinyish.

add HTTP::Tinyish

---

META.list

It appears that jpve is not available to maintain the module at this time, given no response on pull requests for over 3 months. I am willing to maintain the module in the mean time.

Take over maintenance of perl6-pod-to-markdown

---

META.list

See https://github.com/ShaneKilkelly/perl6-http-router-blind

Add HTTP::Router::Blind to ecosystem

---

META.list

[Digest::xxHash](https://github.com/atweiden/digest-xxhash), originally by [Bartłomiej Palmowski](https://github.com/Rotwang/digest-xxhash).

add Digest::xxHash

---

META.list

RPi::Device::DS18B20 provides support for the DS18B20 family of temperature sensors.

Added RPi::Device::DS18B20 to ecosystem.

---

META.list

See https://github.com/dankogai/p6-num-hexfloat/

Add Num::HexFloat to ecosystem

---

META.list

Email::Notmuch is a binding for the NotmuchMail mail search library.
https://notmuchmail.org/

add the Email::Notmuch module

---

META.list

Arguably it should be an Acme:: module, but let me know what you think.

Add perl6-slang-roman

---

META.list

Automatic creation of private accessor for private attribute
See: https://github.com/pierre-vigier/Perl6-AttrX-PrivateAccessor

Add Attrx::PrivateAccessor to ecosystem

---

META.list

Sorry, I forgot a path element in my package name in the URL. Fixed now and old URL will redirect.

apologies, fixed package repo name

---

META.list

A libtranslate wrapper that mangles text similarly to yoleaux's `.mangle` command

Add Acme::Mangle

---

META.list

See https://github.com/Gnouc/p6-linux-process-signalinfo

Add Linux::Process::SignalInfo to ecosystem

---

META.list

See https://github.com/Sufrostico/perl6-wiringpi/
Perl6 wrapper for the wiringpi C library (http://wiringpi.com)

Add RPI::Wiring::Pi to the ecosystem

---

META.list

Repo: https://github.com/jamesalbert/JSON-WebToken

added JSON-WebToken

---

META.list

Just a port of a really little module. I wonder is it that App::Whiff that listed [here](https://github.com/perl6/perl6-most-wanted/blob/master/most-wanted/modules.md#ipc)? If so, we need to update modules.md.

Add App::Whiff

---

META.list

Port of Path::Map from Perl5 with extended functionality.
See https://github.com/fjwhittle/p6-Path-Map

Add Path::Map to the ecosystem

---

META.list

Semaphore readers writers pattern also called  lightswitch

new module Semaphore::ReadersWriters

---

META.list

Compare two data structures in depth similarly to is-deeply(), but ignore some differences, e.g. untyped and typed arrays and hashes.
I personally find it quite useful for writing tests for functions that return elaborate daa structures containing typed arrays and hashes; writing out the fulll definition of the expected structure gets quite burdensome without this.

Add Test::Deeply::Relaxed to the ecosystem.

---

META.list

Hi,
This module provides a getopts() function somewhat similar to the one in Perl 5's Getopt::Std module.  I needed one since I want all my programs, in whatever language they may be written, to have the same command-line interface - for both finger memory and automated testing.
Thanks in advance for considering Yet Another Getopt::*  Module! :)
G'luck,
Peter

Add Getopt::Std - POSIX getopt(3) options processing.

---

META.list

Partly implemented PKCS #5 with Key derivation function PBKDF2 from RFC2898

PKCS #5 with PBKDF2

---

META.list

Sparrowdo module to install CPAN modules using App::cpm - a fast CPAN module installer.

Sparrowdo module to install CPAN modules using App::cpm - a fast CPAN module installer.

---

META.list

This is a plugin for IRC::Client, counting points attributed to users.

Add IRC::Client::Plugin::UserPoints

---

META.list

JavaScript minifier module for Perl 6. This is a port of the Perl JavaScript::Minifier module.

Add JS::Minify module

---

META.list

Pod::Render module and pod-render program to render pod to html using Pod::To:HTML and markdown using Pod::To::Markdown. First can also be converted to pdf using wkhtmltopdf when installed. The module is a sort of wrapper to add better css support.

Pod::Render module

---

META.list

Sparrowdo module to manage Ruby gems via Ruby bundler.

Add  Sparrowdo::Ruby::Bundler to ecosystem

---

META.list

Archive::Libarchive::Raw - a NativeCall interface to libarchive.
Archive::Libarchive - an OO interface to libarchive.

Two new modules

---

META.list

Given permission by @perlpilot (see: https://irclog.perlgeek.de/perl6/2017-01-13#i_13915698), I would like to take over maintenance of the Git::Wrapper module.

Take over Git::Wrapper

---

META.list

First release. https://github.com/faraco/perl6-WebService-Gitter/

Added WebService::Gitter to ecosystem

---

META.list

See https://github.com/ronaldxs/Perl6-US-ASCII

Add US-ASCII to ecosystem

---

META.list

I updated the project to current Socket API & merged outstanding pull requests. Given that the current `Net::XMPP` library isn't working at all with the current `Perl 6.c` version, the author is barely active on GitHub and seems to ignore PRs I assume he isn't interested in it any more. May I take over? 
I'm engaged in the XMPP community and currently working on improving and extending the XMPP support for Perl6, so I will actively maintain this project.

Take over Net::XMPP

---

META.list

Sparrowdo::Chef::Client - canonical name  for META file

META.info --> META6.json

---

META.list

My NCurses6 module at
`https://github.com/blippy/perl6-ncurses6`
is obviated by recent changes to upstream:
`https://github.com/azawawi/perl6-ncurses`
Therefore `NCurses6` should be removed as a redundant package

Remove NCurses6 from ecosystem

---

META.list

MinG is a module for working with Minimalist Grammars: a mildly-context-sensitive formalism first described by Edward Stabler in 1996. MinG::S13 is an implementation of Stabler's 2012/2013 parser for Minimalist Grammars.

Added MinG.

---

.travis.yml
.travis/testpackagemeta.pl

This PR adds Travis tests to PR's, and tests if the URL added is reachable, the META is correct and dependecies are installable.
in Travis you should disable the option that it builds every master push since it doesn't know what to do then.

Add travis tests for newly added packages

---

META.list

Update TagLibC url

---

META.list

See https://github.com/CurtTilmes/perl6-primesieve
- [ X ] I **agree** to the usage of the META file as listed [here](https://github.com/perl6/ecosystem#legal).
- [ X ] I have a license field listed in my META file that is one of https://spdx.org/licenses

Add Math::Primesieve to ecosystem

---

META.list

Add module to easily send messages to Slack using a webhook.
------
Please let me know if anything is amiss and needs to be fixed.

Add WebService::Slack::Webhook

---

META.list

I removed the IO::Prompt entry because I uploaded it to cpan instead.

Remove IO::Prompt because it is uploaded to cpan

---

META.list

Adding META entry for Format::Lisp

---

META.list

I will move it shortly to CPAN, promise.
( I know I can accept the PR, don't want to bother everyone, I'll wait for the tests to pass and I'll accept it)

Adds Wikidata::API

---

META.list

Data::StaticTable added.

---

META.list

This added Perl 6 package is a port of the famous Eric Elliott's CUID JavaScript package (see http://usecuid.org :link:).
In this case make sure you have a …

CUID generator package.

---

META.list

Playing with Slangs by adding an alternative ternary operator …

Added Slang-AltTernary

---

META.list

Add a module called FanFou to ecosystem …

Add FanFou to ecosystem

---

META.list

Update the link to the `META.json` file.
---- …

Move Git::Wrapper to GitLab

---

META.list

See https://github.com/kalkin/Ddt …

Add update for Ddt to v0.5.3

---

META.list

Pod::To::Latex converts Pod6 documents to latex. …

Add Pod::To::Latex to ecosystem

---

META.list

This fixes the commit 518af6f212e900bfcdb794282695b8a973051d32.
- included back all the previous versions of Ddt.
- latest Ddt version uses also a tagged version.
See also ugexe's comment [here](https://github.com/perl6/ecosystem/pull/403#issuecomment-408608887)

Fix "Add update for Ddt to v0.5.3"

---

META.list

Update META.list - Moved Term::Choose, Term::Choose::Util and Term::TablePrint to CPAN

---

META.list

I don't know if it's relevant, but I've also uploaded a tarball of tag 0.0.1 to PAUSE: http://pause.perl.org/pub/PAUSE/authors/id/T/TM/TMTVL/Perl6/.

Add Zodiac::Chinese (https://github.com/tmtvl/Zodiac-Chinese)

---

META.list

Simple and flexible color color conversion module for Perl 6

add CCColor

---

META.list

Reverts perl6/ecosystem#430
There's still something to fix in the META6.json, please check the travis report.

Revert "Update META.list with the BCP57 module"

---

META.list

Adds Test::Script::Output to the ecosystem

---

META.list

Add Net::RCON module to P6 ecosystem

---

META.list

Add the Fluent localization framework

Add Fluent

---

META.list

(Actually moving it, but modules.perl6.org does not seem to have caught it)

Add Unicode Security

---

META.list

see https://gitlab.com/lembark/Perl6-FindBin

Add FindBin to ecosystem

---

.travis/testpackagemeta.p6

An attempt to fix https://github.com/perl6/ecosystem/issues/452
Checked it locally with some newline commits, warnings are gone.

Skip empty lines in diff

---

META.list

Add jsonhound "a system for parsing JSON data structures and identifying anomalies" (https://github.com/oposs/jsonhound) to ecosytem.

Add jsonhound to ecosystem

---

META.list

This version is community-maintained as part of the perl6 repos. It also contains a new version, 0.3.5

Switches to new version

---

META.list

This module can be removed from p6c ecosystem because it is now on CPAN:
- https://modules.perl6.org/dist/Operator::dB:cpan:ALLSOPP

Migrate Operator::dB to CPAN

---

META.list

renamed paths for Email::Valid and Sys::IP modules

---

META.list

https://github.com/hythm7/Grid
Adding `Grid` to p6c. Please note that this is an updated version of the module, previous version of the module is on CPAN. 

Add Grid to p6c

---

META.list

Should be added in anticipation of the Day 15 advent calendar

Added Regex::FuzzyToken

---

META.list

Added HomoGlypher - tool for handling similarly looking characters in strings

---

META.list

A shaped-array console-rendering function.

Adds Array::Shaped::Console

---

META.list

See https://github.com/tinmarino/nogil
Add Slang::Nogil link  to META a Slang to permit scalars with no Sigil in their declaration and use:
```raku
use Slang::Nogil;
local = "value";
say local;  # OUTPUT: "value"
sub fct(param) {
say param;
}
fct("argument");  # OUTPUT: "argument"
```
PS : I prefer here than CPAN because I am under active dev.

Add Slang::Nogil module link to META

---

META.list

Add Services::PortMapping to the ecosystem

---

META.list

...the module is on CPAN and should be taken from there rather than from the source repo.

Remove ReadWriteLock from META.list

---

META.list

This is essentially a change of ownership, due to the prior version failing to install (and preventing other depending modules to do so)

Changes pointing to fork.

---

META.list

Use the right URL

---

META.list

Change repo for distribution

---

META.list

Distribution contains Pod::To::HTML, Pod::To::MarkDown, and a Graphical README.md generator from Pod in Module file. Generates TOC and Glossary and puts them in HTML. Customisable CSS and favicon.
Implements P<> format code (old Pod::To::HTML does not do this).
Pod::To::HTML in this distribution passes all old Pod::To::HTML tests
All output determined by customisable Templates (Mustache engine but this can be changed by subclassing)
Lots of Documentation on usage and subclassing.

Add Generic Pod Renderer to ecosystem

---

META.list

Adding Intl::Usertimezone to the list

---

META.list

URL: https://github.com/codesections/pod-literate

Add Pod::Literate

---

META.list

Raku needs more Acme, and I was bored.

Add Acme::OwO to ecosystem

---

META.list

Updated p6->raku, track rename
--

track rename

---

META.list

This is the re-release of a couple of modules that have been adopted by the community.

Moves to new location

---

META.list

The link to the Meta file for Bailador was adjusted to use `main` in 0294679ce9697953ebff2e0e456af61bf278e0da by @szabgab
However, currently that URL returns a 404, while the one pointing to `master` returns the correct file.

Fix target for Bailador

---

META.list

Let's see if we can get this one the first try

Add Intl::Prompt::YesNo to ecosystem

---

META.list

The repo URL for `Command::Despatch` has changed from `p6` -> `raku`. This PR reflects that change in the ecosystem.

Update repo URL for Command::Despatch

---

META.list

Makes, inter alia, a README.md from POD6 inside a .pm6 / .rakumod file.  
https://raw.githubusercontent.com/finanalyst/raku-pod-extraction/master/META6.json

Add raku-pod-extraction to Ecosystem

---

META.list

(can we get it on the first try this time?)

Add Intl::Format::Number to ecosystem

---

META.list

Add Intl::Format::DateTime to the ecosystem

---

META.list

Creates a Collection version of Raku Documentation. https://github.com/finanalyst/collection-raku-documentation
Currently, static files generated with this system can be seen at http://raku.finanalyst.org

Add Collection-Raku-Documentation

---

META.list

See https://modules.raku.org/dist/Pod::To::Markdown:cpan:SOFTMOTH

Pod::To::Markdown has moved to CPAN

---

META.list

Changes to new location, waiting for new (upcoming) version. This deprecates the old one.

Changes name and auth

---

META.list

Math::Root uses `main` rather than `master`, the fact that master works is just GitHub trying to be helpful. Unfortunately this helpfulness doesn't extend to their GraphQL API.
This change fixes https://gitlab.com/raku-land/raku-land/-/issues/18

Fix Math::Root's branch

---

META.list

Development has been moved to zef, which has now seen a release

Remove AI-FANN from p6c

---

META.list

Like #598 this change is needed to make them resolve via the GraphQL API that Raku Land uses and therefore show up on [raku.land](https://raku.land).

Update a few repos from "master" to "main"

---

META.list

The repo has changed to from "Ed25519" to "ed25519-raku" and the default branch from "master" to "main".

Update Ed25519 URL

---

META.list

Related to the discussion of https://github.com/dagurval/p6-Time-Duration/issues/14. @masukomi has taken over the module, updated the file to META6.json among other things, and published it on the "zef ecosystem".

Time::Duration moved to fez

---

META.list

It continues its life at https://github.com/raku-community-modules/Raku-Data-MessagePack. Contributions welcome!

Remove Data::MessagePack

---

META.list

Because it is providing almost daily updates without ever increasing the version number, causing false positives in updates and etc.
The REA contains an older version of Sustenance, so people will still be able to install it.

Remove Sustenance

---

META.list

Install hasn't worked for years, users of it clone it and use that.

Doc isn't meant to be installed

---

META.list

It lives on the zef ecosystem now.

Remove WebService::AWS::Auth::V4

---

META.list

It has been revived and is now living in zef's ecosystem

Remove GlotIO

---

META.list

Perhaps both would be good to go.
This one was a fork of fork of the other one, more lagging behind than the original one. The original one is released both here and on CPAN. The only known module that might have depended on this (Shell::DSL) didn't have the metadata pinned so even that was already retrieving the other one.

Removing one of the Fcntl repos

---

META.list

It lives in the zef ecosystem now

Remove Test::Output

---

META.list

I'm inclined to think this can be removed.
https://github.com/adaptiveoptics/HTML-Tag/issues/3 I maintain this distribution as my own, for all intents and purposes. It shouldn't be considered still available. It will still on REA from what I understand so nothing breaks but no new code should use it.

Remove old HTML::Tag

---

META.list

It has been living on zef for quite a while.
https://raku.land/zef:guifa/DateTime::Timezones

Remove DateTime::Timezones

---

META.list

I don't think I will actively maintain these modules anymore.
So I think it's fine to simply remove them.
Of course, if someone want to use these modules, then just install them from github.com directly:
```
zef install https://github.com/skaji/foo-module.git
```
---

remove my modules
